name: pricing_cards
description: Awesome pricing cards
version: 0.0.6
repository: https://github.com/f2acode/pricing_cards

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter
  badges: ^2.0.0-nullsafety.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
